## checking normality of features
If majority are normal will proceed with normal standardization, otherwise will use feature ranking to normalize

In [1]:


from scipy.stats import shapiro
import numpy as np
import pickle
import pandas as pd
from sklearn.preprocessing import QuantileTransformer


#importing data

try:
    with open('frameVectorAnnots.pkl', 'rb') as f:
        annots = pickle.load(f)
except:
    print("Error")

In [3]:
#stacking all frames into matrix
frameList = [] 

frameIds = [] 

for day in annots:
    for operation in annots[day]:
        for frame in annots[day][operation]:
            frameList.append(frame['frameVector'])
            frameIds.append((day, operation, frame['frameIdx']))


frameMatrix = np.array(frameList)
print(np.shape(frameMatrix))

#------converting matrix into pandas data frame--

#creating cols and rows
dfCols = []
dfRows = []

interpersonIdx = 1
tableFeatIdx = 1
for i in range(1, np.shape(frameMatrix)[1]+1):
    if i <=50:
        dfCols.append(f"Gpd_{i}")

    elif i == 51:
        dfCols.append(f"Num_clinicians")
    
    elif i>=52 and i<=55:
        dfCols.append(f"Table_feature_{tableFeatIdx}")
        tableFeatIdx+=1
    
    else: 
        dfCols.append(f"Interperson_feature_{interpersonIdx}")
        interpersonIdx+=1

for i in range(1, np.shape(frameMatrix)[0]+1):
    dfRows.append(f"Frame_{i}")

(626, 64)

In [4]:
print(dfCols)

['Gpd_1', 'Gpd_2', 'Gpd_3', 'Gpd_4', 'Gpd_5', 'Gpd_6', 'Gpd_7', 'Gpd_8', 'Gpd_9', 'Gpd_10', 'Gpd_11', 'Gpd_12', 'Gpd_13', 'Gpd_14', 'Gpd_15', 'Gpd_16', 'Gpd_17', 'Gpd_18', 'Gpd_19', 'Gpd_20', 'Gpd_21', 'Gpd_22', 'Gpd_23', 'Gpd_24', 'Gpd_25', 'Gpd_26', 'Gpd_27', 'Gpd_28', 'Gpd_29', 'Gpd_30', 'Gpd_31', 'Gpd_32', 'Gpd_33', 'Gpd_34', 'Gpd_35', 'Gpd_36', 'Gpd_37', 'Gpd_38', 'Gpd_39', 'Gpd_40', 'Gpd_41', 'Gpd_42', 'Gpd_43', 'Gpd_44', 'Gpd_45', 'Gpd_46', 'Gpd_47', 'Gpd_48', 'Gpd_49', 'Gpd_50', 'Num_clinicians', 'Table_feature_1', 'Table_feature_2', 'Table_feature_3', 'Table_feature_4', 'Interperson_feature_1', 'Interperson_feature_2', 'Interperson_feature_3', 'Interperson_feature_4', 'Interperson_feature_5', 'Interperson_feature_6', 'Interperson_feature_7', 'Interperson_feature_8', 'Interperson_feature_9']

In [5]:
frameVectorDf = pd.DataFrame(
    frameMatrix,
    columns = dfCols,
    index = dfRows
)

frameVectorDf.head()

,Gpd_1,Gpd_2,Gpd_3,Gpd_4,Gpd_5,Gpd_6,Gpd_7,Gpd_8,Gpd_9,Gpd_10,...,Table_feature_4,Interperson_feature_1,Interperson_feature_2,Interperson_feature_3,Interperson_feature_4,Interperson_feature_5,Interperson_feature_6,Interperson_feature_7,Interperson_feature_8,Interperson_feature_9
Frame_1,9.522396,9.745949,-2.441483,-2.424845,0.847117,-3.612987,-7.905068,-4.840728,7.682698,2.057512,...,1767.585850,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Frame_2,-6.240740,7.566539,4.392485,-3.616573,8.635847,-11.345625,-5.310072,4.286849,0.439230,3.040247,...,2622.616756,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Frame_3,-7.432102,-9.433077,-2.599083,-2.519187,6.199976,1.432799,-7.219241,7.671942,0.163997,3.052592,...,2445.534774,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Frame_4,-10.756118,-3.976860,-1.695456,-4.020653,6.824022,-1.232486,-3.858355,-1.802732,6.092485,-1.278292,...,2456.068758,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Frame_5,-9.633286,-4.889347,0.764947,-1.182092,8.913971,3.765080,-4.183628,3.302828,1.759320,2.955471,...,2400.928740,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# computes shapiro wilk for each in feature in the data frame
    # Ho: data is normally distributed vs Ha: data is non normally distributed
# returns a dataframe showing which features are normally distributed and which arent
def computeShapiro(df, alpha = 0.05):
    results = []
    rows  = [] 
    cols = ["Normality"] 
    for colName, colData in df.items():
        rows.append(colName)

        #checking normality
        _, p = shapiro(colData)
        normality = 0 if p<=alpha else 1   #1 if data is normal, 0 if not
        results.append(normality)

    featureDistrib = pd.DataFrame(
        results,
        columns = cols,
        index = rows
    )

    #compute percentage of normally distributed features
    normalFeatures = len(featureDistrib.query('Normality == 1'))

    return featureDistrib, normalFeatures

In [7]:
distrib, numNormal = computeShapiro(frameVectorDf)

print(f"{numNormal}/64 features are normally distributed")
distrib.head(64)

8/64 features are normally distributed

                       Normality
Gpd_1                          0
Gpd_2                          1
Gpd_3                          0
Gpd_4                          1
Gpd_5                          0
...                          ...
Interperson_feature_5          0
Interperson_feature_6          0
Interperson_feature_7          0
Interperson_feature_8          0
Interperson_feature_9          0

[64 rows x 1 columns]

In [8]:
print(distrib.query('Normality == 1'))

        Normality
Gpd_2           1
Gpd_4           1
Gpd_11          1
Gpd_12          1
Gpd_15          1
Gpd_22          1
Gpd_24          1
Gpd_44          1

In [9]:
distrib, numNormal = computeShapiro(frameVectorDf, 0.01)

print(f"{numNormal}/64 features are normally distributed")

10/64 features are normally distributed

Majority of features are non normal, thus we will proceed with feature ranking

In [10]:
# maps output to uniform distribution [0-1]
# random_state controls small random noise to handle tied values , setting it ensures reproducibility
#default n_quantiles = 100 so we change it
qt = QuantileTransformer(output_distribution='uniform', n_quantiles=626, random_state=42) 
frameMatrixScaled = qt.fit_transform(frameMatrix)

In [11]:
##applying equal weighting to feature groups <-- this step can be swapped with ahp or anything else
w_gpd = 1/50
w_table = 1/4
w_inter = 1/9

gpdGrp = frameMatrixScaled[:, :50] * w_gpd
tableGrp = frameMatrixScaled[:, 50:55] * w_table
interpersonGrp = frameMatrixScaled[:, 55:] * w_inter
weightedFrames = np.concatenate([gpdGrp, tableGrp, interpersonGrp], axis=1)

In [12]:
print(np.shape(weightedFrames))

(626, 64)

In [13]:
#------converting matrix into pandas data frame--

#creating cols and rows
dfCols = []
dfRows = []

interpersonIdx = 1
tableFeatIdx = 1
for i in range(1, np.shape(weightedFrames)[1] + 1):  
    if i <=50:
        dfCols.append(f"Gpd_{i}")

    elif i == 51:
        dfCols.append(f"Num_clinicians")
    
    elif i>=52 and i<=55:
        dfCols.append(f"Table_feature_{tableFeatIdx}")
        tableFeatIdx+=1
    
    else: 
        dfCols.append(f"Interperson_feature_{interpersonIdx}")
        interpersonIdx+=1

for i in range(1, np.shape(weightedFrames)[0]+1):
    dfRows.append(f"Frame_{i}")


scaledFrameDf = pd.DataFrame(
    weightedFrames,
    columns = dfCols,
    index = dfRows
)

scaledFrameDf.head()

,Gpd_1,Gpd_2,Gpd_3,Gpd_4,Gpd_5,Gpd_6,Gpd_7,Gpd_8,Gpd_9,Gpd_10,...,Table_feature_4,Interperson_feature_1,Interperson_feature_2,Interperson_feature_3,Interperson_feature_4,Interperson_feature_5,Interperson_feature_6,Interperson_feature_7,Interperson_feature_8,Interperson_feature_9
Frame_1,0.016192,0.017760,0.006176,0.006720,0.011904,0.003840,0.000320,0.001728,0.019360,0.014464,...,0.0864,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Frame_2,0.006112,0.016512,0.015680,0.004960,0.019040,0.000384,0.001920,0.017408,0.011776,0.016384,...,0.2104,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Frame_3,0.004928,0.001952,0.006112,0.006592,0.017920,0.013216,0.000576,0.019456,0.010944,0.016448,...,0.1660,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Frame_4,0.001280,0.006240,0.006944,0.004384,0.018208,0.007584,0.003520,0.005856,0.018912,0.007360,...,0.1704,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Frame_5,0.002176,0.005280,0.010400,0.008704,0.019136,0.016576,0.003200,0.016064,0.014848,0.016288,...,0.1540,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
print(scaledFrameDf.to_string())

              Gpd_1     Gpd_2     Gpd_3     Gpd_4     Gpd_5     Gpd_6     Gpd_7     Gpd_8     Gpd_9    Gpd_10    Gpd_11    Gpd_12    Gpd_13    Gpd_14    Gpd_15    Gpd_16    Gpd_17    Gpd_18    Gpd_19    Gpd_20    Gpd_21    Gpd_22    Gpd_23    Gpd_24    Gpd_25    Gpd_26    Gpd_27    Gpd_28    Gpd_29    Gpd_30    Gpd_31    Gpd_32    Gpd_33    Gpd_34    Gpd_35    Gpd_36    Gpd_37    Gpd_38    Gpd_39    Gpd_40    Gpd_41    Gpd_42    Gpd_43    Gpd_44    Gpd_45    Gpd_46    Gpd_47    Gpd_48    Gpd_49    Gpd_50  Num_clinicians  Table_feature_1  Table_feature_2  Table_feature_3  Table_feature_4  Interperson_feature_1  Interperson_feature_2  Interperson_feature_3  Interperson_feature_4  Interperson_feature_5  Interperson_feature_6  Interperson_feature_7  Interperson_feature_8  Interperson_feature_9
Frame_1    0.016192  0.017760  0.006176  0.006720  0.011904  0.003840  0.000320  0.001728  0.019360  0.014464  0.019360  0.002144  0.019168  0.009600  0.001088  0.013600  0.009376  0.013664  0.002080  0.003840  0.002560  0.001792  0.007168  0.009408  0.007968  0.016672  0.011520  0.000160  0.015200  0.003904  0.002144  0.004640  0.016160  0.010208  0.016768  0.016160  0.010848  0.016480  0.012736  0.005184  0.017312  0.014816  0.014176  0.004480  0.005504  0.000256  0.005408  0.011040  0.007776  0.004064          0.0000             0.00           0.0388           0.0000           0.0864               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_2    0.006112  0.016512  0.015680  0.004960  0.019040  0.000384  0.001920  0.017408  0.011776  0.016384  0.009696  0.003328  0.018176  0.011168  0.008640  0.002464  0.000736  0.017952  0.005856  0.007168  0.014272  0.012672  0.017632  0.018176  0.017856  0.014016  0.003712  0.018464  0.011200  0.008768  0.010592  0.016672  0.018752  0.015712  0.000160  0.000544  0.018912  0.010208  0.015360  0.007456  0.010272  0.007328  0.014816  0.009504  0.005152  0.000320  0.011072  0.004320  0.012544  0.000640          0.0000             0.00           0.1948           0.0000           0.2104               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_3    0.004928  0.001952  0.006112  0.006592  0.017920  0.013216  0.000576  0.019456  0.010944  0.016448  0.003872  0.018144  0.008992  0.012352  0.008736  0.017920  0.017504  0.005568  0.019904  0.009952  0.014304  0.003648  0.012832  0.008160  0.003040  0.015616  0.000448  0.007136  0.001824  0.018176  0.017248  0.000672  0.006464  0.004448  0.018816  0.017440  0.016960  0.012416  0.015488  0.001184  0.002752  0.017120  0.018592  0.018912  0.000224  0.002336  0.017024  0.009824  0.014048  0.001280          0.0000             0.00           0.1508           0.0000           0.1660               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_4    0.001280  0.006240  0.006944  0.004384  0.018208  0.007584  0.003520  0.005856  0.018912  0.007360  0.009440  0.016320  0.003744  0.012768  0.007328  0.001408  0.001920  0.000768  0.003840  0.009984  0.000192  0.011552  0.015744  0.004288  0.003872  0.003488  0.003424  0.018496  0.002944  0.011648  0.015392  0.019136  0.008160  0.018336  0.011904  0.011776  0.010080  0.017248  0.018464  0.006112  0.019488  0.002176  0.000608  0.015968  0.018496  0.009504  0.016512  0.003552  0.013760  0.003520          0.0000             0.00           0.1548           0.0000           0.1704               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_5    0.002176  0.005280  0.010400  0.008704  0.019136  0.016576  0.003200  0.016064  0.014848  0.016288  0.003968  0.015296  0.001952  0.018080  0.006080  0.013216  0.017920  0.001120  0.019936  0.006432  0.005056  0.012224  0.018240  0.005088  0.001216  0.011424  0.000128  0.019040  0.004512  0.015328  0.018816  0.014912  0.002624  0.019200  0.015040  0.005120  0.004736  0.018080  0.011584  0.005216  0.019424  0.008928  0.004576  0.002880  0.014720  0.005792  0.008000  0.004896  0.006176  0.002784          0.0000             0.00           0.1388           0.0000           0.1540               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_6    0.006848  0.018912  0.015584  0.010592  0.015232  0.013504  0.019744  0.014272  0.000000  0.018368  0.009152  0.018688  0.018496  0.014912  0.000256  0.019520  0.019584  0.007840  0.015008  0.004032  0.017088  0.005248  0.016320  0.011072  0.017792  0.005824  0.012960  0.016096  0.008256  0.001344  0.005568  0.010656  0.018816  0.016160  0.008512  0.008960  0.002112  0.001184  0.016352  0.002112  0.019296  0.019616  0.008672  0.014528  0.017888  0.005248  0.019680  0.019392  0.018816  0.002720          0.0000             0.00           0.2232           0.2500           0.2284               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_7    0.013792  0.001312  0.003968  0.019168  0.001280  0.008864  0.001376  0.016320  0.003584  0.006912  0.001696  0.005920  0.001344  0.018496  0.003328  0.000800  0.019008  0.006016  0.011328  0.019488  0.009536  0.010016  0.016064  0.017152  0.018048  0.006848  0.019296  0.003008  0.001664  0.011520  0.007008  0.012736  0.004448  0.000640  0.007744  0.018016  0.012800  0.006880  0.019328  0.009376  0.004960  0.007040  0.017472  0.015520  0.012576  0.003776  0.018176  0.003008  0.017920  0.016032          0.0000             0.00           0.0188           0.0000           0.0532               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_8    0.016864  0.018464  0.012768  0.015232  0.010464  0.007936  0.000128  0.005280  0.019424  0.014208  0.019168  0.008032  0.017184  0.013248  0.004192  0.004576  0.015072  0.015328  0.006752  0.000288  0.000896  0.000128  0.005792  0.003008  0.018400  0.004800  0.007904  0.000032  0.006688  0.003168  0.013184  0.012416  0.014720  0.013312  0.013824  0.016416  0.017376  0.017184  0.010400  0.003584  0.019072  0.019200  0.007488  0.010208  0.010848  0.001664  0.000512  0.016832  0.011872  0.015904          0.0000             0.00           0.0208           0.0000           0.0552               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_9    0.009504  0.016480  0.001120  0.019616  0.011936  0.013056  0.001504  0.019616  0.012416  0.003968  0.001824  0.006624  0.010912  0.013312  0.013760  0.012512  0.000800  0.018624  0.014752  0.003040  0.019584  0.016128  0.007968  0.001856  0.008800  0.001280  0.009440  0.011104  0.005312  0.007104  0.018240  0.003104  0.010336  0.013600  0.004576  0.010400  0.005248  0.000160  0.011904  0.011680  0.012480  0.001824  0.002880  0.015488  0.002656  0.014016  0.011104  0.017696  0.007520  0.012512          0.0000             0.00           0.0560           0.2500           0.1044               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_10   0.016992  0.009696  0.014240  0.001600  0.011712  0.003648  0.018720  0.014848  0.009088  0.000768  0.000000  0.002528  0.014944  0.002336  0.010336  0.015968  0.018336  0.016928  0.019520  0.009376  0.004096  0.014272  0.005216  0.001280  0.008864  0.017248  0.002912  0.008512  0.008800  0.000384  0.011872  0.001568  0.016256  0.011808  0.014240  0.007872  0.003328  0.010560  0.005984  0.009216  0.018240  0.001664  0.003904  0.012544  0.010752  0.010720  0.001472  0.015392  0.002528  0.016992          0.0000             0.00           0.0700           0.2500           0.1148               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_11   0.016288  0.006944  0.006656  0.000640  0.002624  0.002688  0.005696  0.014752  0.014912  0.005344  0.001088  0.000416  0.014656  0.007936  0.016768  0.012192  0.018240  0.016384  0.015808  0.006272  0.001888  0.015328  0.001120  0.004608  0.007584  0.019552  0.011456  0.008672  0.007648  0.008096  0.001952  0.002400  0.019424  0.005632  0.006720  0.005856  0.001504  0.000640  0.001312  0.002976  0.019104  0.001216  0.015328  0.008768  0.015104  0.019424  0.001408  0.004416  0.004352  0.019200          0.0000             0.00           0.0600           0.0000           0.1072               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_12   0.009888  0.017568  0.006752  0.002816  0.016704  0.015776  0.000032  0.011776  0.019264  0.017504  0.002400  0.002944  0.013152  0.001184  0.001504  0.003456  0.010912  0.017472  0.010304  0.003744  0.016832  0.001600  0.008416  0.017440  0.014368  0.001920  0.004416  0.003808  0.002048  0.000960  0.010880  0.001632  0.013088  0.018848  0.019520  0.007136  0.012896  0.006688  0.013120  0.010016  0.011040  0.002784  0.016736  0.011104  0.006016  0.001216  0.019296  0.000640  0.005728  0.010656          0.0000             0.00           0.1432           0.0000           0.1576               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_13   0.004576  0.015008  0.008704  0.001504  0.013696  0.018016  0.019840  0.002816  0.014496  0.003264  0.007968  0.000672  0.001312  0.019200  0.017760  0.009856  0.000448  0.016320  0.017792  0.018304  0.009472  0.008192  0.002080  0.010816  0.018176  0.019776  0.000320  0.006496  0.004384  0.014368  0.017184  0.003456  0.009504  0.016320  0.001888  0.013184  0.000640  0.004992  0.018848  0.008928  0.011712  0.001792  0.013728  0.015456  0.018144  0.018624  0.007840  0.011104  0.002848  0.009408          0.0000             0.00           0.1532           0.0000           0.1688               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_14   0.004800  0.000768  0.013056  0.003552  0.014720  0.012384  0.002432  0.014144  0.005440  0.015488  0.008288  0.015488  0.011520  0.000640  0.000448  0.009920  0.013376  0.014144  0.019776  0.016832  0.012608  0.013760  0.004768  0.008608  0.006080  0.011712  0.005120  0.013408  0.003104  0.005280  0.013376  0.000480  0.009856  0.017184  0.013312  0.010944  0.007328  0.009472  0.006400  0.004320  0.000640  0.009792  0.001568  0.000672  0.000928  0.010112  0.001312  0.013472  0.017696  0.003808          0.0000             0.00           0.1692           0.0000           0.1872               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_15   0.012256  0.004512  0.000672  0.019136  0.001760  0.011424  0.016096  0.005344  0.011072  0.000992  0.016960  0.017056  0.001056  0.015456  0.012288  0.005664  0.012512  0.002688  0.015648  0.016512  0.009632  0.012640  0.001280  0.019104  0.019168  0.019232  0.011712  0.000256  0.016896  0.009024  0.008416  0.006784  0.001088  0.008608  0.010048  0.019456  0.001472  0.005184  0.001248  0.001216  0.000704  0.000128  0.008832  0.006752  0.019584  0.014624  0.018368  0.007296  0.018272  0.002208          0.0000             0.00           0.0956           0.2500           0.1284               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_16   0.007616  0.001152  0.018624  0.019200  0.003584  0.017184  0.003360  0.016608  0.002176  0.014784  0.003040  0.019904  0.009088  0.003904  0.007360  0.015200  0.018368  0.014656  0.001472  0.003680  0.003072  0.018816  0.007264  0.001600  0.012672  0.003008  0.007072  0.009728  0.009632  0.003584  0.012384  0.018816  0.002080  0.011232  0.006528  0.004768  0.004192  0.012320  0.011552  0.017856  0.004096  0.013376  0.019552  0.006528  0.005760  0.009984  0.010816  0.011488  0.003136  0.008896          0.0000             0.00           0.2068           0.0000           0.2172               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_17   0.000288  0.004960  0.014336  0.018432  0.005856  0.008992  0.013568  0.007520  0.007008  0.000480  0.004832  0.013600  0.017760  0.000160  0.004672  0.005984  0.010016  0.001408  0.018944  0.012320  0.013888  0.015488  0.006528  0.000864  0.018272  0.018368  0.003328  0.015264  0.011072  0.002656  0.003520  0.008064  0.017152  0.014624  0.000672  0.016672  0.016640  0.015808  0.013952  0.016800  0.019680  0.002304  0.009792  0.011360  0.009088  0.011552  0.000384  0.006944  0.010656  0.016000          0.0000             0.00           0.1996           0.0000           0.2128               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_18   0.004544  0.008224  0.001984  0.013344  0.012192  0.000640  0.007520  0.015296  0.008544  0.003808  0.001984  0.018880  0.010944  0.001344  0.019168  0.001216  0.001760  0.005856  0.015520  0.013568  0.003712  0.012096  0.019232  0.010464  0.014464  0.013952  0.001984  0.012416  0.003712  0.009952  0.011712  0.013376  0.005088  0.016992  0.001696  0.009088  0.007456  0.017952  0.008544  0.015904  0.008160  0.003648  0.010144  0.014720  0.016512  0.002720  0.008768  0.019584  0.002656  0.012288          0.0000             0.00           0.2408           0.0000           0.2424               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_19   0.000672  0.011424  0.008512  0.018112  0.018336  0.000576  0.016928  0.017600  0.000992  0.001792  0.014368  0.017152  0.003968  0.009312  0.011360  0.005184  0.011808  0.016064  0.018336  0.005696  0.000160  0.015936  0.008640  0.017280  0.009152  0.015840  0.016384  0.016416  0.000000  0.011712  0.010080  0.002688  0.005632  0.009248  0.013920  0.000288  0.005184  0.001344  0.019264  0.016832  0.000800  0.016608  0.005760  0.008960  0.017728  0.008544  0.007232  0.015104  0.001248  0.000192          0.0000             0.00           0.1588           0.0000           0.1760               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000               0.000000
Frame_20   0.015264  0.013696  0.004288  0.017760  0.007488  0.011136  0.000800  0.016768  0.015104  0.008544  0.002944  0.009376  0.009792  0.009568  0.013536  0.002112  0.008768  0.013760  0.014688  0.012256  0.002336  0.004448  0.002464  0.001632  0.007040  0.014560  0.010176  0.006272  0.013088  0.007744  0.016416  0.010592  0.002144  0.006304  0.014816  0.003424  0.003968  0.016448  0.013472  0.015360  0.011200  0.012640  0.008800  0.009344  0.008384  0.018080  0.009664  0.015072  0.017280  0.007968          0.1694             0.00           0.0168           0.1292           0.0432               0.076978               0.000000               0.086578               0.073422               0.094933               0.000000               0.087644               0.000000               0.097778
Frame_21   0.011584  0.008416  0.011968  0.010528  0.014560  0.015968  0.005536  0.018304  0.014368  0.010400  0.011744  0.009728  0.014016  0.015680  0.012416  0.002912  0.007488  0.007776  0.019040  0.011488  0.018784  0.010144  0.009408  0.003584  0.008416  0.010016  0.008288  0.019520  0.001472  0.016544  0.004256  0.000544  0.018080  0.004768  0.016416  0.004704  0.019424  0.017120  0.015200  0.019008  0.011168  0.005504  0.009248  0.006816  0.001440  0.019776  0.017280  0.019616  0.018560  0.012800          0.2280             0.00           0.0748           0.0940           0.0744               0.083378               0.098133               0.080178               0.084800               0.109156               0.098311               0.109511               0.097244               0.105244
Frame_22   0.010240  0.001824  0.015872  0.002912  0.006464  0.004288  0.004608  0.013088  0.014816  0.008704  0.007904  0.010304  0.009632  0.003488  0.009696  0.006112  0.010976  0.011616  0.012960  0.004896  0.012128  0.006560  0.010240  0.003072  0.017440  0.013984  0.018528  0.006304  0.004064  0.003552  0.005184  0.007456  0.012160  0.017344  0.002816  0.004960  0.012416  0.009920  0.007520  0.005152  0.016384  0.002912  0.018560  0.017344  0.001600  0.016608  0.007200  0.012896  0.006624  0.003072          0.2280             0.00           0.0712           0.0940           0.0416               0.094578               0.106489               0.081778               0.102222               0.096000               0.096533               0.097244               0.097600               0.094578
Frame_23   0.012416  0.009984  0.005600  0.003520  0.002016  0.011776  0.004480  0.008064  0.013088  0.012384  0.010016  0.008352  0.014400  0.003808  0.017664  0.005728  0.016320  0.015392  0.016640  0.005056  0.009184  0.005408  0.005440  0.006496  0.007456  0.015552  0.017792  0.004736  0.001280  0.004544  0.006176  0.013728  0.011456  0.009440  0.011680  0.003808  0.005696  0.005344  0.014656  0.012288  0.015680  0.019136  0.007136  0.003904  0.007840  0.011840  0.011040  0.016000  0.012672  0.000928          0.2280             0.00           0.0804           0.1722           0.0436               0.097778               0.109156               0.078400               0.107556               0.073067               0.107733               0.085689               0.107911               0.062933

## Regroup per operation

In [15]:
#group per operation again 
for day in annots:
    print(annots[day].keys())
    print(len(annots[day]))

dict_keys(['operation_6', 'operation_3', 'operation_9', 'operation_5', 'operation_8', 'operation_4', 'operation_7', 'operation_11', 'operation_2', 'operation_10', 'operation_1'])
11
dict_keys(['operation_1', 'operation_9', 'operation_2', 'operation_6', 'operation_7', 'operation_5', 'operation_8', 'operation_11', 'operation_4', 'operation_3', 'operation_10'])
11
dict_keys(['operation_1', 'operation_2', 'operation_3'])
3
dict_keys(['operation_1'])
1

In [16]:
for day in annots:
    for operation in annots[day]:
        print(f"{day} {operation}: {len(annots[day][operation])}")

day3 operation_6: 7
day3 operation_3: 23
day3 operation_9: 8
day3 operation_5: 33
day3 operation_8: 10
day3 operation_4: 21
day3 operation_7: 21
day3 operation_11: 15
day3 operation_2: 17
day3 operation_10: 13
day3 operation_1: 7
day2 operation_1: 105
day2 operation_9: 23
day2 operation_2: 97
day2 operation_6: 12
day2 operation_7: 7
day2 operation_5: 11
day2 operation_8: 11
day2 operation_11: 4
day2 operation_4: 8
day2 operation_3: 2
day2 operation_10: 2
day4 operation_1: 70
day4 operation_2: 41
day4 operation_3: 5
day1 operation_1: 53

In [17]:
OP_RANGES = [
    (0, 52), #day 1
    (53, 157), (158, 254), (257, 264), (265, 275), (276, 287), (288, 294), (295, 305), (306, 328), (331, 334), #day 2: dropped operations 3 (255,256) and 10 (329,330) because theyre only 2 frames long
    (335, 341), (342, 358), (359, 381), (382, 402), (403, 435), (436, 442), (443, 463), (464, 473), (474, 481), (482, 494), (495, 509), #day 3
    (510, 579), (580, 620), (621, 625) #day 4 
]

len(OP_RANGES)

24

In [18]:
print(type(scaledFrameDf))

<class 'pandas.core.frame.DataFrame'>

In [19]:
#converting pandas df to numpy arr
frames = scaledFrameDf.to_numpy()

In [20]:
operationVectors = []
for range in OP_RANGES:
    op = frames[range[0]:range[1]+1,]
    operationVectors.append(op)

operationVectors[0]

array([[0.016192  , 0.01776   , 0.006176  , ..., 0.        , 0.        ,
        0.        ],
       [0.006112  , 0.016512  , 0.01568   , ..., 0.        , 0.        ,
        0.        ],
       [0.004928  , 0.001952  , 0.006112  , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.002048  , 0.010688  , 0.013632  , ..., 0.07253333, 0.        ,
        0.08248889],
       [0.008736  , 0.004704  , 0.00544   , ..., 0.10506667, 0.        ,
        0.10897778],
       [0.015104  , 0.017696  , 0.005824  , ..., 0.06897778, 0.        ,
        0.07804444]], shape=(53, 64))

In [23]:
print(len(operationVectors))

24

In [22]:
print(type(operationVectors))

<class 'list'>

In [24]:
#exporting so we can work with operation list elsewhere

import pickle 

with open('operationList.pkl', 'wb') as f:
    pickle.dump(operationVectors, f)